create table IF NOT EXISTS comment
(
    id       bigint generated by default as identity
    constraint pk_comment
    primary key,
    time     timestamp,
    username varchar(50),
    text     text,
    news_id  bigint
    );


TRUNCATE TABLE comment RESTART IDENTITY;

INSERT INTO comment (time, text, username, news_id)
VALUES (NOW(), 'Comment 1', 'Patrik', 1),
       (NOW(), 'Comment 2', 'Charly', 1),
       (NOW(), 'Comment 1 Sarah', 'Polly', 2),
       (NOW(), 'Comment 2', 'Sarah', 2);