create table IF NOT EXISTS news
(
    id    bigint generated by default as identity
        constraint pk_news
            primary key,
    time  timestamp,
    text  text,
    title varchar(255)
);

TRUNCATE TABLE news RESTART IDENTITY;

INSERT INTO news (time, title, text)
VALUES (NOW(), 'News Title', 'News content for News Title'),
       (NOW(), 'News 2', 'Content news 2'),
       (NOW(), 'News 3', 'Content news 3');