create table IF NOT EXISTS comment
(
    id       bigint generated by default as identity
        constraint pk_comment
            primary key,
    time     timestamp,
    username varchar(50),
    text     text,
    news_id  bigint
);

create table IF NOT EXISTS news
(
    id    bigint generated by default as identity
    constraint pk_news
    primary key,
    time  timestamp,
    text  text,
    title varchar(255)
    );

TRUNCATE TABLE news RESTART IDENTITY;
TRUNCATE TABLE comment RESTART IDENTITY;

INSERT INTO news (time, title, text)
VALUES (NOW(), 'News Title', 'News content for News Title'),
(NOW(), 'News 2', 'Content news 2'),
(NOW(), 'News 3', 'Content news 3');


INSERT INTO comment (time, text, username, news_id)
VALUES (NOW(), 'Comment 1', 'Patrik', 1),
       (NOW(), 'Comment 2', 'Charly', 1),
       (NOW(), 'Comment 1 Sarah back', 'Polly', 2),
       (NOW(), 'Comment 2', 'Sarah', 2);