spring:
  application:
    name: comments-service
  cloud:
    config:
      fail-fast: true
  profiles:
    active: prod
#    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://localhost:8888

---
spring:
  config:
    activate:
      on-profile: prod
    import: optional:configserver:http://server-config:8888

---
spring:
  config:
    activate:
      on-profile: test
    import: optional:configserver:http://localhost:8888
